/*
** NOTE: This file is generated by Gulp and should not be edited directly!
** Any changes made directly to this file will be overwritten next time its asset group is processed by Gulp.
*/

(function () {

    var checkRedirectToDomain = function () {
        if ($('.js-redirect-type-select').val() === 'RedirectToDomain') {
            $('.js-redirect-domain-field').css('display', 'block');
        } else {
            $('.js-redirect-domain-field').css('display', 'hidden');
        }
    };

    $('.js-redirect-type-select').on('change', checkRedirectToDomain);

    checkRedirectToDomain();
})();
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNldHRpbmdzLmVkaXRvci5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsQUFMQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBIiwiZmlsZSI6InNldHRpbmdzLmVkaXRvci5qcyIsInNvdXJjZXNDb250ZW50IjpbIihmdW5jdGlvbiAoKSB7XHJcblxyXG4gICAgdmFyIGNoZWNrUmVkaXJlY3RUb0RvbWFpbiA9IGZ1bmN0aW9uICgpIHtcclxuICAgICAgICBpZiAoJCgnLmpzLXJlZGlyZWN0LXR5cGUtc2VsZWN0JykudmFsKCkgPT09ICdSZWRpcmVjdFRvRG9tYWluJykge1xyXG4gICAgICAgICAgICAkKCcuanMtcmVkaXJlY3QtZG9tYWluLWZpZWxkJykuY3NzKCdkaXNwbGF5JywgJ2Jsb2NrJyk7XHJcbiAgICAgICAgfSBlbHNlIHtcclxuICAgICAgICAgICAgJCgnLmpzLXJlZGlyZWN0LWRvbWFpbi1maWVsZCcpLmNzcygnZGlzcGxheScsICdoaWRkZW4nKTtcclxuICAgICAgICB9XHJcbiAgICB9O1xyXG5cclxuICAgICQoJy5qcy1yZWRpcmVjdC10eXBlLXNlbGVjdCcpLm9uKCdjaGFuZ2UnLCBjaGVja1JlZGlyZWN0VG9Eb21haW4pO1xyXG5cclxuICAgIGNoZWNrUmVkaXJlY3RUb0RvbWFpbigpO1xyXG59KSgpOyJdLCJzb3VyY2VSb290IjoiL3NvdXJjZS8ifQ==
